-- DEPRECATED — disputes live in the canonical schema:
--   supabase/reports-blocks-disputes.sql
--
-- If you only need a legacy-table patch (raised_by / detail columns):
--   supabase/disputes-raised-by.sql
